name: notifier_plus
description: "Notifier Plus is a Flutter plugin that improves reactive data handling, merges consecutive state updates, and prevents redundant rebuilds. It provides specialized notifiers (both synchronous and asynchronous), composable watchers, and useful utilities (like OneCallTask) to streamline state management and enhance performance."
version: 0.1.0
repository: https://github.com/tachibana-shin/notifier_plus
homepage: https://github.com/tachibana-shin/notifier_plus

environment:
  sdk: ^3.6.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.25.8
