name: notifier_plus
description: "Notifier Plus is a Flutter plugin that improves reactive data handling, merges consecutive state updates, and prevents redundant rebuilds. It provides specialized notifiers (both synchronous and asynchronous), composable watchers, and useful utilities (like OneCallTask) to streamline state management and enhance performance."
version: 0.1.0
repository: https://github.com/tachibana-shin/notifier_plus
homepage: https://github.com/tachibana-shin/notifier_plus

environment:
  sdk: ^3.6.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.25.8

# Removing 'publish_to: none' so it's ready for public publishing.
# By default, if publish_to is not specified, it targets 'https://pub.dev'.

flutter:
  plugin:
    platforms:
      android:
        # The 'package' is the Android package name where the plugin class is located.
        package: com.tachibana_shin.notifier_plus
        pluginClass: NotifierPlusPlugin
      ios:
        pluginClass: NotifierPlusPlugin
      macos:
        pluginClass: NotifierPlusPlugin
      linux:
        pluginClass: NotifierPlusPlugin
      windows:
        pluginClass: NotifierPlusPlugin
      web:
        pluginClass: NotifierPlusWebPlugin
        fileName: lib/notifier_plus_web.dart
# Adjust or remove entries below as needed.

# Example showing how to add assets for the plugin:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

# Example showing how to add fonts for the plugin:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
